name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '13', '12', '11' ]
    name: Build in Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
      - run: yarn build
